#!/usr/bin/env node
var rottenbay = require('./lib/rottenbay');
var multi = require('multimeter')(process);
var count = 0, total = -1;

rottenbay.get(function (movies){
  console.log('Done:', movies);
});
multi.drop({before: 'Crunching movies: ['}, function (bar) {
  var iv = setInterval(function () {
    bar.percent(count/total*100);
    if (bar.percent() >= 100){
      multi.charm.destroy();
      clearInterval(iv);
    }
  }, 25);
});
multi.charm.on('^C', process.exit);
rottenbay.progress.on('done', function (){ count=1; total=1; });
rottenbay.progress.on('movie', function (movie){
  count++;
});
rottenbay.progress.on('movieList', function (movieList){
  total = movieList.length;
});
